[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'self'; 'unsafe-inline'; connect-src 'self'; img-src 'self'; base-uri 'self';"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "0"
